export const EDITORIAL_PRINCIPLES_AND_TONE = `=== CATEGORY 1: EDITORIAL PRINCIPLES & TONE ===

Introduction to style and tone  
This style guide is for writers and editors of Broadsheet editorial copy, as well as Broadsheet Studio staff. It is a handy reference for key points of style and Australian English usage as followed by Broadsheet. It’s also an aid in clarifying common misunderstandings regarding punctuation, tone and grammar. The style guide is the primary reference for Broadsheet editorial content. It is not exhaustive, however. If still in doubt, consult the Broadsheet subediting team.
Typos and Mistakes  
Typos make the site look sloppy and ruin credibility. Care and attention must be taken to ensure that what appears is spelt correctly. From the user’s point of view, if you can’t spell or get names right, why would anything else you write be accurate? Exercise care and attention when typing. Once a story is completed, stop, slow down and read each word deliberately and carefully. An extra few minutes will make a lot of difference. 
COARSE LANGUAGE 
In quotes, swearing is usually okay, but best avoided in a Broadsheet author’s own voice. Only quote coarse language and swearing when essential to the story. We do not censor expletives either on the site or in subtitles. 
FIRST PERSON 
First-person pronouns (I and me) should be used mindfully and sparingly for Broadsheet. There are certain articles where it works well or is indeed part of the premise of the piece. But in a profile of a venue such as a first look or coming soon, it is usually not appropriate. The first person can be a useful entry point for travel, health and wellness or fashion stories, but again, do so carefully. One useful way of approaching it is: only use “I” if the point, observation or detail in question absolutely cannot be expressed without it. Additionally, the first-person perspective needs to be established early on in a story – it doesn’t work if it’s suddenly introduced in a piece’s final third, when the tone has already been established. 
INDIGENOUS
Upper case I when referring to Aboriginal and Torres Strait Islander people (eg Indigenous artist), otherwise lower case (eg plants indigenous to the region). Likewise, Aboriginal is capitalised when referring to Australian Aboriginal people. The word "native" is not banned. Update September 2025: we now also capitalise Indigenous when it refers to any Indigenous peoples internationally. We should also be proactive about specifying Indigenous nations, Country, language groups etc. For example, you might make reference to “the Gadigal people of the Eora Nation”. If this is missing in a story about Indigenous people, we should seek it out, while acknowledging some people won’t want to share this. See the Australian Government Style Manual for more detailed discussion of this topic. The below is from the Narragunnawali educational resources website: It is often best practice to use ‘Aboriginal and Torres Strait Islander’ when referring generally to Aboriginal and Torres Strait Islander peoples. ‘Aboriginal’ (and less commonly accepted variants such as ‘Aboriginals’ or ‘Aborigines’) alone is also not inclusive of the diversity of cultures and identities across Australia, for which reason it should be accompanied by ‘peoples’ in the plural. Similarly, as a standalone term, ‘Aboriginal’ is not inclusive of Torres Strait Islander peoples, and reference to both Aboriginal and Torres Strait Islander peoples should be spelt out where the intention is to refer to all First Peoples of Australia. Pluralised reference terms such as 'First Peoples' or ‘First Nations’ are also acceptable language, and respectfully encompass the diversity of Aboriginal and Torres Strait Islander cultures and identities. Correspondingly, pluralisation should extend to generalised reference to Aboriginal and Torres Strait Islander ‘histories,’ ‘perspectives,’ ‘ways of being,’ ‘contributions,’ and so forth. We also use caps when referring to various Indigenous concepts, including Country, Elders, and Traditional Owners. Dual naming for places: when we use the Indigenous name alongside its Anglo name, we use a forward slash and place the Indigenous name first. As of April 2026, we add a space before and after the slash, so: Naarm / Melbourne, K’gari / Fraser Island and so on. 


JARGON
Use jargon, technical words, scientific words, foreign words etc only if they’re commonly understood. If you must use them and they’re not widely understood, provide a definition or, failing that, link to an authoritative explanation. 


RURAL/REGIONAL
When writing about places in Australia that are outside capital cities, “regional” and “rural” are not synonymous. According to the Macquarie, regional means “of or relating to the smaller cities, towns and areas that lie beyond a major capital city: the need to develop regional Australia.” So that could mean Bendigo in Victoria, the Blue Mountains in NSW or Margaret River in WA. Rural means “of, relating to, or characteristic of the country (as distinguished from towns or cities), country life, or country people; rustic”. It’s used to describe remote towns, places and regions – perhaps a farmstead or a remote farming region, or a small town that’s really distant from any major regional centre. A few examples: the town of Nelson in Victoria, Kimo Estate in NSW, Winton in Queensland. These categories and descriptions should serve a general guide – there might be locations that seem like they could fit into both, so use your judgement to decide which term fits best. If you’re unsure, it’s worth checking maps on state government websites, as most will classify different parts of the state into urban, regional, rural and/or remote. 


Miscellaneous style notes  
Avoid all language that engages in body or food shaming. At the end of articles that discuss or touch on rape, domestic violence or sexual assault, we put this note at the end in italics: If you would like to speak with someone about an experience you have had, or would like information, please call 1800Respect on 1800 737 732 or visit 1800respect.org.au. At the end of an article that discusses or touches on depression, anxiety and mental illness, add this note at the bottom of the story in italics: If you or someone you know is experiencing depression or anxiety, call Lifeline Australia on 13 11 14 or visit lifeline.org.au. When referring to migrants and refugees, keep this from the BuzzFeed style guide in mind: Refer to people fleeing their countries as "people" (and variations thereof: people fleeing war, people escaping Eritrea, people fleeing for Europe, people escaping the war in Syria, etc.). This allows us to humanise the crisis. 
Use "refugee" when referring to a person who is forced to leave his/her home or country to escape war, persecution or natural disaster. 
Use "migrant" when referring to someone seeking economic or other opportunity. 
When we aggregate news  
We only aggregate when we absolutely have to, but it does happen from time to time and there are two important things to remember when we do. 
ALWAYS include a line that we reached out to the subject/s for comment, because we always do. This is very important. It shows our audience we did try to reach out to verify and report out the news ourselves. (e.g. Broadsheet has reached out to Shark Fin House for comment.) 
If we reach out to more than one subject, that should be noted. I.e. Broadsheet has reached out to Joe Smith and Smith Dining for comment. 
If the subject hasn't yet got back to us, the above Shark Fin House sentence is sufficient. If they do eventually get back to us, we should add their comments to the piece. 
If a subject declines to comment, we must say that. I.e. Joe Smith and Smith Dining declined to comment about the closure. 
If a subject declines to comment and explains why, include that information to give our readers as much clarity as possible. I.e. Joe Smith declined to comment about the closure due to ongoing legal proceedings. 
Never start a sentence with the name of the attributable publication. Put the 'according to...' or 'X publication reported...' at the end of the sentence. Firstly, the news isn't that the Age or others reported something, it's that X has happened to X – so lead with the news, not the publication that reported it. Secondly, while we must attribute and link out to the other publications, we needn't give them such prominent space in the sentence hierarchy. 
When using quotes sourced from another publication, credit both the speaker and the publication they spoke to on first mention. Use past tense, like so: “I couldn’t believe the scale of the wage theft,” former bartender Phil Upperglass told the Age. 

`;
