export const DEFAULT_MACQUARIE_ENTRIES: { [key: string]: string } = {
  // -ise endings
  "organise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'organize'.",
  "organised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'organized'.",
  "organising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'organizing'.",
  "organisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'organization'.",
  "organisations": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'organizations'.",
  "realise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'realize'.",
  "realised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'realized'.",
  "realising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'realizing'.",
  "realisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'realization'.",
  "realisations": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'realizations'.",
  "socialise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'socialize'.",
  "socialised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'socialized'.",
  "socialising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'socializing'.",
  "socialisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'socialization'.",
  "finalise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'finalize'.",
  "finalised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'finalized'.",
  "finalising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'finalizing'.",
  "finalisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'finalization'.",
  "categorise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'categorize'.",
  "categorised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'categorized'.",
  "categorising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'categorizing'.",
  "categorisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'categorization'.",
  "polarise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'polarize'.",
  "polarised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'polarized'.",
  "polarising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'polarizing'.",
  "polarisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'polarization'.",
  "prioritise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'prioritize'.",
  "prioritised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'prioritized'.",
  "prioritising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'prioritizing'.",
  "prioritisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'prioritization'.",
  "localise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'localize'.",
  "localised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'localized'.",
  "localising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'localizing'.",
  "localisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'localization'.",
  "emphasise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'emphasize'.",
  "emphasised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'emphasized'.",
  "emphasising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'emphasizing'.",
  "synthesise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'synthesize'.",
  "synthesised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'synthesized'.",
  "synthesising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'synthesizing'.",
  "civilise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'civilize'.",
  "civilised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'civilized'.",
  "civilising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'civilizing'.",
  "civilisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'civilization'.",
  "colonise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'colonize'.",
  "colonised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'colonized'.",
  "colonising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'colonizing'.",
  "colonisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'colonization'.",
  "customise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'customize'.",
  "customised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'customized'.",
  "customising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'customizing'.",
  "customisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'customization'.",
  "digitise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'digitize'.",
  "digitised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'digitized'.",
  "digitising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'digitizing'.",
  "digitisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'digitization'.",
  "energise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'energize'.",
  "energised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'energized'.",
  "energising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'energizing'.",
  "familiarise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'familiarize'.",
  "familiarised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'familiarized'.",
  "familiarising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'familiarizing'.",
  "familiarisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'familiarization'.",
  "generalise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'generalize'.",
  "generalised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'generalized'.",
  "generalising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'generalizing'.",
  "generalisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'generalization'.",
  "globalise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'globalize'.",
  "globalised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'globalized'.",
  "globalising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'globalizing'.",
  "globalisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'globalization'.",
  "hospitalise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'hospitalize'.",
  "hospitalised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'hospitalized'.",
  "hospitalising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'hospitalizing'.",
  "hospitalisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'hospitalization'.",
  "industrialise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'industrialize'.",
  "industrialised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'industrialized'.",
  "industrialising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'industrializing'.",
  "industrialisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'industrialization'.",
  "initialise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'initialize'.",
  "initialised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'initialized'.",
  "initialising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'initializing'.",
  "initialisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'initialization'.",
  "maximise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'maximize'.",
  "maximised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'maximized'.",
  "maximising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'maximizing'.",
  "maximisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'maximization'.",
  "minimise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'minimize'.",
  "minimised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'minimized'.",
  "minimising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'minimizing'.",
  "minimisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'minimization'.",
  "mobilise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'mobilize'.",
  "mobilised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'mobilized'.",
  "mobilising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'mobilizing'.",
  "mobilisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'mobilization'.",
  "modernise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'modernize'.",
  "modernised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'modernized'.",
  "modernising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'modernizing'.",
  "modernisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'modernization'.",
  "monopolise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'monopolize'.",
  "monopolised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'monopolized'.",
  "monopolising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'monopolizing'.",
  "monopolisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'monopolization'.",
  "nationalise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'nationalize'.",
  "nationalised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'nationalized'.",
  "nationalising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'nationalizing'.",
  "nationalisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'nationalization'.",
  "neutralise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'neutralize'.",
  "neutralised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'neutralized'.",
  "neutralising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'neutralizing'.",
  "neutralisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'neutralization'.",
  "normalise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'normalize'.",
  "normalised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'normalized'.",
  "normalising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'normalizing'.",
  "normalisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'normalization'.",
  "optimise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'optimize'.",
  "optimised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'optimized'.",
  "optimising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'optimizing'.",
  "optimisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'optimization'.",
  "patronise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'patronize'.",
  "patronised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'patronized'.",
  "patronising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'patronizing'.",
  "personalise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'personalize'.",
  "personalised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'personalized'.",
  "personalising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'personalizing'.",
  "personalisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'personalization'.",
  "popularise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'popularize'.",
  "popularised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'popularized'.",
  "popularising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'popularizing'.",
  "popularisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'popularization'.",
  "rationalise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'rationalize'.",
  "rationalised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'rationalized'.",
  "rationalising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'rationalizing'.",
  "rationalisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'rationalization'.",
  "recognise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'recognize'.",
  "recognised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'recognized'.",
  "recognising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'recognizing'.",
  "recognition": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'recognition'.",
  "revolutionise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'revolutionize'.",
  "revolutionised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'revolutionized'.",
  "revolutionising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'revolutionizing'.",
  "sensitise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'sensitize'.",
  "sensitised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'sensitized'.",
  "sensitising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'sensitizing'.",
  "sensitisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'sensitization'.",
  "stabilise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'stabilize'.",
  "stabilised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'stabilized'.",
  "stabilising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'stabilizing'.",
  "stabilisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'stabilization'.",
  "standardise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'standardize'.",
  "standardised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'standardized'.",
  "standardising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'standardizing'.",
  "standardisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'standardization'.",
  "subsidise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'subsidize'.",
  "subsidised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'subsidized'.",
  "subsidising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'subsidizing'.",
  "subsidisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'subsidization'.",
  "summarise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'summarize'.",
  "summarised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'summarized'.",
  "summarising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'summarizing'.",
  "summarisation": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'summarization'.",
  "symbolise": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'symbolize'.",
  "symbolised": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'symbolized'.",
  "symbolising": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'symbolizing'.",

  // -our endings
  "colour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'color'.",
  "coloured": "Preferred Australian spelling (Macquarie Dictionary).",
  "colouring": "Preferred Australian spelling (Macquarie Dictionary).",
  "colourful": "Preferred Australian spelling (Macquarie Dictionary).",
  "flavour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'flavor'.",
  "flavoured": "Preferred Australian spelling (Macquarie Dictionary).",
  "flavouring": "Preferred Australian spelling (Macquarie Dictionary).",
  "flavourful": "Preferred Australian spelling (Macquarie Dictionary).",
  "honour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'honor'.",
  "honoured": "Preferred Australian spelling (Macquarie Dictionary).",
  "honouring": "Preferred Australian spelling (Macquarie Dictionary).",
  "honourable": "Preferred Australian spelling (Macquarie Dictionary).",
  "humour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'humor'.",
  "humoured": "Preferred Australian spelling (Macquarie Dictionary).",
  "humouring": "Preferred Australian spelling (Macquarie Dictionary).",
  "humorous": "Preferred Australian spelling (Macquarie Dictionary).",
  "labour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'labor'.",
  "laboured": "Preferred Australian spelling (Macquarie Dictionary).",
  "labouring": "Preferred Australian spelling (Macquarie Dictionary).",
  "labourer": "Preferred Australian spelling (Macquarie Dictionary).",
  "neighbour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'neighbor'.",
  "neighboured": "Preferred Australian spelling (Macquarie Dictionary).",
  "neighbouring": "Preferred Australian spelling (Macquarie Dictionary).",
  "neighbourhood": "Preferred Australian spelling (Macquarie Dictionary).",
  "behaviour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'behavior'.",
  "behavioural": "Preferred Australian spelling (Macquarie Dictionary).",
  "rumour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'rumor'.",
  "rumoured": "Preferred Australian spelling (Macquarie Dictionary).",
  "favour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'favor'.",
  "favoured": "Preferred Australian spelling (Macquarie Dictionary).",
  "favouring": "Preferred Australian spelling (Macquarie Dictionary).",
  "favourite": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'favorite'.",
  "favourable": "Preferred Australian spelling (Macquarie Dictionary).",
  "harbour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'harbor'.",
  "harboured": "Preferred Australian spelling (Macquarie Dictionary).",
  "vigour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'vigor'.",
  "vigorous": "Preferred Australian spelling (Macquarie Dictionary).",
  "glamour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'glamor'.",
  "glamorous": "Preferred Australian spelling (Macquarie Dictionary).",
  "candour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'candor'.",
  "rancour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'rancor'.",
  "ardour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'ardor'.",
  "splendour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'splendor'.",
  "armour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'armor'.",
  "armoured": "Preferred Australian spelling (Macquarie Dictionary).",
  "saviour": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'savior'.",

  // -re endings
  "theatre": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'theater'.",
  "theatres": "Preferred Australian spelling (Macquarie Dictionary).",
  "theatrical": "Preferred Australian spelling (Macquarie Dictionary).",
  "centre": "Preferred Australian spelling (Macquarie Dictionary). Do not use 'center'.",
  "centred": "Preferred Australian spelling (Macquarie Dictionary).",
  "centring": "Preferred Australian spelling (Macquarie Dictionary).",
  "central": "Preferred Australian spelling (Macquarie Dictionary).",
  "decentralise": "Preferred Australian spelling (Macquarie Dictionary).",
  "fibre": "Preferred Australian spelling (Macquarie Dictionary). Use 'fibre', not 'fiber'.",
  "fibres": "Preferred Australian spelling (Macquarie Dictionary).",
  "fibrous": "Preferred Australian spelling (Macquarie Dictionary).",
  "metre": "Preferred Australian spelling (Macquarie Dictionary). Use 'metre' (length/unit), not 'meter' (except for measuring devices like water meter).",
  "metres": "Preferred Australian spelling (Macquarie Dictionary).",
  "metric": "Preferred Australian spelling (Macquarie Dictionary).",
  "calibre": "Preferred Australian spelling (Macquarie Dictionary). Use 'calibre', not 'caliber'.",
  "calibres": "Preferred Australian spelling (Macquarie Dictionary).",
  "lustre": "Preferred Australian spelling (Macquarie Dictionary). Use 'lustre', not 'luster'.",
  "lustrous": "Preferred Australian spelling (Macquarie Dictionary).",
  "sombre": "Preferred Australian spelling (Macquarie Dictionary). Use 'sombre', not 'somber'.",
  "centrepiece": "Preferred Australian spelling (Macquarie Dictionary). Use 'centrepiece', not 'centerpiece'.",
  "epicentre": "Preferred Australian spelling (Macquarie Dictionary). Use 'epicentre', not 'epicenter'.",
  "louvre": "Preferred Australian spelling (Macquarie Dictionary). Use 'louvre', not 'louver'.",
  "louvres": "Preferred Australian spelling (Macquarie Dictionary).",
  "manoeuvre": "Preferred Australian spelling (Macquarie Dictionary). Use 'manoeuvre', not 'maneuver'.",
  "manoeuvres": "Preferred Australian spelling (Macquarie Dictionary).",
  "manoeuvered": "Preferred Australian spelling (Macquarie Dictionary).",
  "manoeuvering": "Preferred Australian spelling (Macquarie Dictionary).",
  "spectre": "Preferred Australian spelling (Macquarie Dictionary). Use 'spectre', not 'specter'.",
  "spectres": "Preferred Australian spelling (Macquarie Dictionary).",
  "spectral": "Preferred Australian spelling (Macquarie Dictionary).",

  // Double L endings
  "travelled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'travelled', not 'traveled'.",
  "travelling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'travelling', not 'traveling'.",
  "traveller": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'traveller', not 'traveler'.",
  "travellers": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'travellers', not 'travelers'.",
  "cancelled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'cancelled', not 'canceled'.",
  "cancelling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'cancelling', not 'canceling'.",
  "cancellation": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'cancellation', not 'cancelation'.",
  "cancellations": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'cancellations', not 'cancelations'.",
  "dialled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'dialled', not 'dialed'.",
  "dialling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'dialling', not 'dialing'.",
  "labelled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'labelled', not 'labeled'.",
  "labelling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'labelling', not 'labeling'.",
  "channelled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'channelled', not 'channeled'.",
  "channelling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'channelling', not 'channeling'.",
  "fuelled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'fuelled', not 'fueled'.",
  "fuelling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'fuelling', not 'fueling'.",
  "modelled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'modelled', not 'modeled'.",
  "modelling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'modelling', not 'modeling'.",
  "signalled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'signalled', not 'signaled'.",
  "signalling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'signalling', not 'signaling'.",
  "rivalled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'rivalled', not 'rivaled'.",
  "rivalling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'rivalling', not 'rivaling'.",
  "marvelled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'marvelled', not 'marveled'.",
  "marvelling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'marvelling', not 'marveling'.",
  "marvellous": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'marvellous', not 'marvelous'.",
  "equalled": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'equalled', not 'equaled'.",
  "equalling": "Preferred Australian spelling (Macquarie Dictionary). Use double 'll': 'equalling', not 'equaling'.",
  "jeweller": "Preferred Australian spelling (Macquarie Dictionary). Use 'jeweller', not 'jeweler'.",
  "jewellers": "Preferred Australian spelling (Macquarie Dictionary).",
  "jewellery": "Preferred Australian spelling (Macquarie Dictionary). Use 'jewellery', not 'jewelry'.",
  "woollen": "Preferred Australian spelling (Macquarie Dictionary). Use 'woollen', not 'woolen'.",

  // -ogue endings
  "catalogue": "Preferred Australian spelling (Macquarie Dictionary). Use 'catalogue', not 'catalog'.",
  "catalogues": "Preferred Australian spelling (Macquarie Dictionary).",
  "cataloguing": "Preferred Australian spelling (Macquarie Dictionary).",
  "dialogue": "Preferred Australian spelling (Macquarie Dictionary). Use 'dialogue', not 'dialog'.",
  "dialogues": "Preferred Australian spelling (Macquarie Dictionary).",
  "prologue": "Preferred Australian spelling (Macquarie Dictionary). Use 'prologue', not 'prolog'.",
  "prologues": "Preferred Australian spelling (Macquarie Dictionary).",
  "epilogue": "Preferred Australian spelling (Macquarie Dictionary). Use 'epilogue', not 'epilog'.",
  "epilogues": "Preferred Australian spelling (Macquarie Dictionary).",
  "analogue": "Preferred Australian spelling (Macquarie Dictionary). Use 'analogue', not 'analog'.",
  "analogues": "Preferred Australian spelling (Macquarie Dictionary).",
  "monologue": "Preferred Australian spelling (Macquarie Dictionary). Use 'monologue', not 'monolog'.",
  "monologues": "Preferred Australian spelling (Macquarie Dictionary).",

  // Common spelling variations / other words
  "licence": "Preferred Australian spelling for the noun form (Macquarie Dictionary) - e.g., 'driving licence'. Note: Use 'license' for the verb form.",
  "licences": "Preferred Australian spelling for the plural noun (Macquarie Dictionary).",
  "practise": "Preferred Australian spelling for the verb form (Macquarie Dictionary) - e.g., 'to practise medicine'. Note: Use 'practice' for the noun.",
  "practises": "Preferred Australian spelling for the verb form (Macquarie Dictionary).",
  "practising": "Preferred Australian spelling for the verb form (Macquarie Dictionary).",
  "grey": "Preferred Australian spelling (Macquarie Dictionary). Use 'grey', not 'gray'.",
  "greyer": "Preferred Australian spelling.",
  "greyest": "Preferred Australian spelling.",
  "cosy": "Preferred Australian spelling (Macquarie Dictionary). Use 'cosy', not 'cozy'.",
  "cosier": "Preferred Australian spelling.",
  "cosiest": "Preferred Australian spelling.",
  "cheque": "Preferred Australian spelling for bank cheques (Macquarie Dictionary). Use 'cheque', not 'check'.",
  "cheques": "Preferred Australian spelling for bank cheques.",
  "draught": "Preferred Australian spelling for draught beer/wind (Macquarie Dictionary). Use 'draught', not 'draft'.",
  "draughts": "Preferred Australian spelling.",
  "syrup": "Preferred Australian spelling (Macquarie Dictionary). Use 'syrup', not 'sirup'.",
  "syrupy": "Preferred Australian spelling.",
  "yoghurt": "Preferred Australian spelling (Macquarie Dictionary). Use 'yoghurt', not 'yogurt'.",
  "artefact": "Preferred Australian spelling (Macquarie Dictionary). Use 'artefact', not 'artifact'.",
  "artefacts": "Preferred Australian spelling.",
  "pyjamas": "Preferred Australian spelling (Macquarie Dictionary). Use 'pyjamas', not 'pajamas'.",
  "speciality": "Preferred Australian spelling in standard print media (Macquarie Dictionary), though 'specialty' is also widely accepted.",
  "specialities": "Preferred Australian spelling.",
  "sulphur": "Preferred Australian spelling in non-scientific print media (Macquarie Dictionary). Use 'sulphur', not 'sulfur' (scientific context only).",
  "coriander": "Standard Australian term (Macquarie Dictionary). Do not use 'cilantro' except when referring strictly to the seeds (coriander seeds) or in US quotes.",
  "shallot": "Preferred Australian term for spring onions/scallions in some regional contexts, or specifically the small bulb (Macquarie Dictionary).",
  "capsicum": "Preferred Australian term (Macquarie Dictionary). Do not use 'bell pepper'.",
  "beetroot": "Preferred Australian term (Macquarie Dictionary). Do not use 'beets' (US)."
};
